"""
Code Agent for KimiGPT
Generates HTML, CSS, and JavaScript code
"""

from typing import Dict, Any
from src.api.api_manager import APIManager


class CodeAgent:
    """Generates website code"""

    def __init__(self, api_manager: APIManager):
        self.api_manager = api_manager

    async def generate_code(self, design_result: Dict[str, Any], content_result: Dict[str, Any], preferences: Dict[str, Any]) -> Dict[str, Any]:
        """Generate website code"""

        design_spec = design_result.get('design_specification', '')
        content = content_result.get('content', '')
        framework = preferences.get('framework', 'vanilla')
        complexity = preferences.get('complexity', 'moderate')

        # Generate HTML
        html_prompt = f"""
Generate a complete, professional HTML5 website based on these specifications:

Design Specifications:
{design_spec}

Content:
{content}

Requirements:
- Framework: {framework}
- Complexity: {complexity}
- Fully responsive design
- Modern, clean code
- SEO-optimized
- Accessibility compliant (WCAG AA)
- Include all necessary sections
- Professional styling

Generate the complete HTML file with embedded CSS and JavaScript. Make it production-ready.
Include proper meta tags, semantic HTML, and modern best practices.

Start directly with <!DOCTYPE html> - no explanations before or after the code.
"""

        try:
            # Generate HTML
            html_code = await self.api_manager.generate_text(html_prompt, "code", 8000)

            # Clean up code (remove markdown code blocks if present)
            html_code = self.clean_code(html_code)

            # Generate additional files if needed
            files = {
                'index.html': html_code,
                'README.md': self.generate_readme(preferences),
            }

            # Generate separate CSS and JS if complexity is advanced
            if complexity == 'advanced':
                css_prompt = "Generate advanced CSS with animations and responsive design for the website. Include modern features like CSS Grid, Flexbox, and smooth animations."
                js_prompt = "Generate JavaScript for interactive features including smooth scrolling, animations, form validation, and dynamic content loading."

                try:
                    css_code = await self.api_manager.generate_text(css_prompt, "code", 4000)
                    js_code = await self.api_manager.generate_text(js_prompt, "code", 4000)

                    files['styles.css'] = self.clean_code(css_code)
                    files['script.js'] = self.clean_code(js_code)
                except:
                    pass  # If additional files fail, still return the main HTML

            return {
                'success': True,
                'files': files,
                'framework': framework,
                'complexity': complexity
            }

        except Exception as e:
            # Fallback to a basic template if generation fails
            return {
                'success': True,
                'files': {
                    'index.html': self.get_fallback_template(content, design_spec),
                    'README.md': self.generate_readme(preferences)
                },
                'framework': framework,
                'note': f'Used fallback template due to: {str(e)}'
            }

    def clean_code(self, code: str) -> str:
        """Remove markdown code blocks and clean code"""
        code = code.strip()

        # Remove markdown code blocks
        if code.startswith('```'):
            lines = code.split('\n')
            if lines[0].startswith('```'):
                lines = lines[1:]
            if lines and lines[-1].startswith('```'):
                lines = lines[:-1]
            code = '\n'.join(lines)

        return code.strip()

    def generate_readme(self, preferences: Dict[str, Any]) -> str:
        """Generate README file"""
        return f"""# {preferences.get('project_name', 'Website')}

Generated by KimiGPT - AI Website Builder

## Features
- Fully responsive design
- Modern and clean interface
- SEO optimized
- Accessibility compliant
- Cross-browser compatible

## Tech Stack
- Framework: {preferences.get('framework', 'HTML/CSS/JS')}
- Complexity: {preferences.get('complexity', 'moderate')}

## Deployment
Simply upload all files to your web hosting provider or open index.html in a browser to preview.

## Generated On
{preferences.get('generated_date', 'N/A')}

---
Built with ❤️ by KimiGPT
"""

    def get_fallback_template(self, content: str, design_spec: str) -> str:
        """Get fallback HTML template"""
        return """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to My Website</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
        }

        .hero {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 100px 20px;
            text-align: center;
        }

        .hero h1 {
            font-size: 3em;
            margin-bottom: 20px;
        }

        .hero p {
            font-size: 1.3em;
            margin-bottom: 30px;
            opacity: 0.9;
        }

        .btn {
            display: inline-block;
            padding: 15px 40px;
            background: white;
            color: #667eea;
            text-decoration: none;
            border-radius: 30px;
            font-weight: 600;
            transition: transform 0.3s ease;
        }

        .btn:hover {
            transform: translateY(-3px);
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 80px 20px;
        }

        .section-title {
            text-align: center;
            font-size: 2.5em;
            margin-bottom: 50px;
        }

        .features {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 40px;
        }

        .feature-card {
            padding: 30px;
            background: #f8f9fa;
            border-radius: 15px;
            transition: transform 0.3s ease;
        }

        .feature-card:hover {
            transform: translateY(-10px);
        }

        .feature-card h3 {
            font-size: 1.5em;
            margin-bottom: 15px;
            color: #667eea;
        }

        footer {
            background: #2d3748;
            color: white;
            text-align: center;
            padding: 40px 20px;
        }

        @media (max-width: 768px) {
            .hero h1 {
                font-size: 2em;
            }

            .features {
                grid-template-columns: 1fr;
            }
        }
    </style>
</head>
<body>
    <section class="hero">
        <h1>Welcome to Your Website</h1>
        <p>Professional solutions for your business</p>
        <a href="#contact" class="btn">Get Started</a>
    </section>

    <div class="container">
        <h2 class="section-title">Our Services</h2>
        <div class="features">
            <div class="feature-card">
                <h3>🚀 Feature One</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore.</p>
            </div>
            <div class="feature-card">
                <h3>💡 Feature Two</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore.</p>
            </div>
            <div class="feature-card">
                <h3>✨ Feature Three</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore.</p>
            </div>
        </div>
    </div>

    <footer>
        <p>&copy; 2024 Your Website. All rights reserved.</p>
        <p>Generated by KimiGPT - AI Website Builder</p>
    </footer>

    <script>
        // Smooth scrolling
        document.querySelectorAll('a[href^="#"]').forEach(anchor => {
            anchor.addEventListener('click', function (e) {
                e.preventDefault();
                const target = document.querySelector(this.getAttribute('href'));
                if (target) {
                    target.scrollIntoView({ behavior: 'smooth' });
                }
            });
        });
    </script>
</body>
</html>
"""
