"""
Deployment Agent for KimiGPT
Packages and prepares website for deployment
"""

from typing import Dict, Any
from pathlib import Path
import shutil
import zipfile
from datetime import datetime


class DeploymentAgent:
    """Handles website packaging and deployment preparation"""

    def __init__(self):
        pass

    async def package(self, code_result: Dict[str, Any], output_dir: Path, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """Package website files"""

        try:
            files = code_result.get('files', {})

            if not files:
                return {
                    'success': False,
                    'error': 'No files to package'
                }

            # Write files to output directory
            written_files = []
            for filename, content in files.items():
                file_path = output_dir / filename

                try:
                    with open(file_path, 'w', encoding='utf-8') as f:
                        f.write(content)
                    written_files.append(str(file_path))
                except Exception as e:
                    print(f"Error writing {filename}: {e}")

            # Create ZIP file
            zip_filename = f"{input_data.get('project_id', 'website')}.zip"
            zip_path = output_dir.parent / zip_filename

            with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
                for file_path in written_files:
                    file_path_obj = Path(file_path)
                    zipf.write(file_path, file_path_obj.name)

            # Create deployment guide
            deployment_guide = self.create_deployment_guide(input_data)
            guide_path = output_dir / 'DEPLOYMENT_GUIDE.md'

            with open(guide_path, 'w', encoding='utf-8') as f:
                f.write(deployment_guide)

            return {
                'success': True,
                'output_dir': str(output_dir),
                'files_written': len(written_files),
                'written_files': written_files,
                'zip_file_path': str(zip_path),
                'zip_filename': zip_filename,
                'deployment_guide': str(guide_path)
            }

        except Exception as e:
            return {
                'success': False,
                'error': str(e)
            }

    def create_deployment_guide(self, input_data: Dict[str, Any]) -> str:
        """Create deployment guide"""
        return f"""# Deployment Guide
## {input_data.get('project_name', 'Your Website')}

Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

### Files Included
- `index.html` - Main website file
- `README.md` - Project documentation
- Additional assets (if any)

### Quick Start
1. Open `index.html` in a web browser to preview locally
2. All files are ready for deployment

### Deployment Options

#### Option 1: Netlify (Recommended)
1. Go to https://www.netlify.com/
2. Drag and drop your files or ZIP file
3. Your site will be live instantly!
4. Free SSL certificate included

#### Option 2: Vercel
1. Go to https://vercel.com/
2. Import your project
3. Deploy with one click
4. Free hosting with custom domain support

#### Option 3: GitHub Pages
1. Create a GitHub repository
2. Upload your files
3. Enable GitHub Pages in settings
4. Your site will be live at username.github.io/repo-name

#### Option 4: Traditional Hosting
1. Get a web hosting account (e.g., Bluehost, HostGator, SiteGround)
2. Upload files via FTP or cPanel File Manager
3. Place files in the public_html or www directory
4. Access your site at your domain name

### Testing Your Website
- Test on multiple browsers (Chrome, Firefox, Safari, Edge)
- Test on mobile devices
- Check all links and buttons
- Verify contact forms work
- Test responsive design by resizing browser window

### Support
For issues or questions:
- Check README.md for project details
- Review the code comments
- Contact your hosting provider for deployment issues

### Next Steps
- ✅ Add custom domain
- ✅ Set up analytics (Google Analytics)
- ✅ Configure SEO meta tags
- ✅ Add social media links
- ✅ Set up contact form backend (if needed)

---
Generated by KimiGPT - AI Website Builder
https://github.com/kimigpt
"""
